# Generated by Django 4.2.3 on 2023-07-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_name_pokemon_names_attack'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='cost',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='attack',
            name='damage',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='attack',
            name='description',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='attack',
            name='names',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='attack',
            name='types',
            field=models.CharField(choices=[('F', 'Fire'), ('G', 'Grass'), ('W', 'Water'), ('L', 'Lightning'), ('P', 'Psychic'), ('C', 'Colorless'), ('D', 'Darkness'), ('M', 'Metal'), ('DR', 'Dragon'), ('F', 'Fairy'), ('FG', 'Fighting')], default='F', max_length=2),
        ),
    ]
