# Generated by Django 4.2.3 on 2023-07-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_attack_cost_attack_damage_attack_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='names',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
