# Generated by Django 4.2.3 on 2023-07-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_attack_description_alter_attack_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoosterPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='BoosterPacks',
            field=models.ManyToManyField(to='main_app.boosterpack'),
        ),
    ]
