# Generated by Django 4.2.3 on 2023-08-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_boosterpack_pokemon_boosterpacks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='BoosterPacks',
            new_name='boosterpacks',
        ),
    ]
